"""Export the analytical schema and table contents to data/processed/.

Produces:
    data/processed/schema.sql       Full DDL for the analytical tables.
    data/processed/<table>.csv      One CSV per dim, fact, and mart, plus a
                                    couple of supporting tables. Geometry
                                    columns are skipped because their binary
                                    representations are unreadable as text.
"""
from __future__ import annotations

import os
import shutil
import subprocess

import pandas as pd
from sqlalchemy import text

from pipeline._http import log
from pipeline.config import PROJECT_ROOT
from pipeline.db import get_engine

OUT_DIR = PROJECT_ROOT / "data" / "processed"

EXPORT_TABLES = [
    "dim_geography",
    "dim_measure",
    "dim_facility",
    "dim_year",
    "fact_places",
    "fact_svi",
    "fact_svi_wide",
    "fact_acs",
    "fact_imr",
    "fact_hospital_quality",
    "fact_hpsa_county",
    "mart_maternal_risk_index",
    "mart_drive_time",
    "mart_double_burden",
    "mart_top20_priority",
    "mart_hrrp_regressivity",
    "svi_county",
    "stg_msdh_imr_race",
]


def export_table(engine, table: str) -> int:
    cols = pd.read_sql(text("""
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = :t
          AND udt_name <> 'geometry'
        ORDER BY ordinal_position
    """), engine, params={"t": table})["column_name"].tolist()

    if not cols:
        log.warning(f"  {table}: no non-geometry columns, skipping")
        return 0

    col_list = ", ".join(f'"{c}"' for c in cols)
    df = pd.read_sql(text(f"SELECT {col_list} FROM {table}"), engine)
    out_path = OUT_DIR / f"{table}.csv"
    df.to_csv(out_path, index=False)
    log.info(f"  {table}: {len(df):,} rows -> {out_path.name}")
    return len(df)


def export_schema(engine) -> None:
    if shutil.which("pg_dump") is None:
        log.warning("pg_dump not found on PATH; skipping schema.sql export")
        return

    db_url = engine.url
    cmd = [
        "pg_dump",
        "--schema-only",
        "--no-owner",
        "--no-privileges",
        "--no-comments",
        "--schema=public",
        "--exclude-table=spatial_ref_sys",
        "--exclude-table=stg_tiger_*",
        "--exclude-table=stg_acs_long",
        "--exclude-table=acs_headline",
        f"--host={db_url.host}",
        f"--port={db_url.port}",
        f"--username={db_url.username}",
        db_url.database,
    ]
    env = {**os.environ, "PGPASSWORD": db_url.password or ""}
    result = subprocess.run(cmd, capture_output=True, text=True, env=env)
    if result.returncode != 0:
        log.warning(f"pg_dump failed: {result.stderr.strip()[:200]}")
        return

    out_path = OUT_DIR / "schema.sql"
    out_path.write_text(result.stdout)
    log.info(f"  schema.sql: {len(result.stdout):,} bytes")


def write_processed_readme() -> None:
    readme = OUT_DIR / "README.md"
    readme.write_text(
        "# Processed data\n"
        "\n"
        "Exported contents of the analytical schema. Regenerated by `make export` "
        "(or as part of `make all`). Each file corresponds to a table in the "
        "PostgreSQL `public` schema.\n"
        "\n"
        "- `schema.sql`: full DDL for the analytical tables.\n"
        "- `dim_*.csv`: dimension tables (geography, measure, facility, year).\n"
        "- `fact_*.csv`: fact tables (PLACES, SVI long, SVI wide, ACS, IMR, hospital quality, HPSA).\n"
        "- `mart_*.csv`: the five analytical marts (MRI, drive time, double burden, top 20 priority, HRRP regressivity).\n"
        "- `svi_county.csv` and `stg_msdh_imr_race.csv`: supporting tables read by the marts and the Q15 disparity query.\n"
        "\n"
        "Geometry columns are omitted from the CSVs because their binary "
        "representations are not human readable. The tract and county polygons "
        "live in `dim_geography.geom` and are reproducible by running "
        "`make extract && make load`.\n"
    )
    log.info(f"  README.md")


def main() -> None:
    log.info("=== Exporting schema and table contents to data/processed/ ===")
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    # Clear any old gitkeep so the export rewrites the directory cleanly
    gitkeep = OUT_DIR / ".gitkeep"
    if gitkeep.exists():
        gitkeep.unlink()

    engine = get_engine()
    export_schema(engine)

    total_rows = 0
    for table in EXPORT_TABLES:
        total_rows += export_table(engine, table)

    write_processed_readme()
    log.info(f"=== Export complete: {len(EXPORT_TABLES)} tables, {total_rows:,} rows total ===")


if __name__ == "__main__":
    main()
